techBoard/views/auth.py
# svicars/views/auth.py

from flask import Flask, Blueprint, render_template, flash, redirect, request, abort, url_for, session
from flask_login import LoginManager, login_required, login_user, logout_user 
from flask_wtf import FlaskForm
from flask_wtf.recaptcha import RecaptchaField
from wtforms import StringField, IntegerField, SubmitField, SelectField, PasswordField
from wtforms.validators import DataRequired, Length, Email, InputRequired, EqualTo
from wtforms.fields.html5 import TelField
from techBoard.models.User import *
from techBoard.models.User import User

import hashlib, uuid

# set blueprint
auth = Blueprint('auth', __name__)



@auth.route('/auth/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        
        user = User()
        user.username = form.username.data 
        user.password = form.password.data.encode('utf-8')

        if(user.makeUserFromCreds()):
            session['user_id'] = user.userID
            login_user(user)
            next = request.args.get('next')
            if next is None or not next.startswith('/'):
                next = url_for('manage.manageIssues')
            return redirect(next)
        else:
            flash('Invalid username or password. ')
    

    return render_template('site/login.html', form=form)



@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


class LoginForm(FlaskForm):
    username = StringField('Username:', validators=[DataRequired(), Length(1,64)])
    password = PasswordField('Password:', validators=[DataRequired()])
    submit = SubmitField('Login')

techBoard/views/manage.py
# views/manage.py

# This view contains all of the resources for managing views


import sys
sys.path.append("..")
from flask import Blueprint, render_template, session, request, jsonify, redirect, url_for
from flask_login import login_required
from flask_wtf import FlaskForm 
from wtforms import StringField, IntegerField, SubmitField, SelectField, TextAreaField, BooleanField, validators
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired, InputRequired, NumberRange, Optional, Length
from techBoard.models.Issue import Issue

from techBoard.models.DBase import connection


# set blueprint
manage = Blueprint('manage', __name__)

# routes
# ========================================


@manage.route('/manage')
@login_required
def manageIssues():
    try:
        c, conn = connection()
        c.execute("SELECT * FROM techBoard.issue WHERE active = 1 OR CURRENT_DATE - modified_date <= 7 ORDER BY created_date DESC;")
        result_set = c.fetchall()
        conn.close()

        return render_template('manage/manageIssues.html', issues=result_set)

    except Exception as e:
        return str(e)

@manage.route('/manage/<int:issueID>', methods=['GET','POST'])
@login_required
def editIssue(issueID):
    # Initialize the form 
    form = issueForm()
    # Attempt to fetch the record
    issue = Issue()
    issue.issueID = issueID
    result = issue.fetch()

    if form.validate_on_submit():
        issue.title = form.title.data
        issue.description = form.description.data
        issue.status = form.status.data
        issue.instructionBox = int(form.instructionBox.data)
        issue.instructions = form.instructions.data
        issue.active = int(form.active.data)
        # Attempt to store the issue
        result = issue.update()
        if result == True:
            return redirect(url_for("manage.manageIssues"))
        else:
            return "<h1>OOPS</h1><p>Something has gone utterley and terribly wrong. {}</p>".format(str(result))


    if result:
        form.title.data = issue.title 
        form.description.data = issue.description
        form.status.data = issue.status 
        form.instructionBox.data = issue.instructionBox
        form.instructions.data = issue.instructions
        form.active.data = issue.active

        return render_template('manage/issue.html', form=form)

    return "Error: Could not find the record"


@manage.route('/manage/create', methods=['GET','POST'])
@login_required
def createIssue():
    form = issueForm()

    if form.is_submitted():
        if form.validate():
            # Process the data 
            issue = Issue()
            issue.title = form.title.data
            issue.description = form.description.data
            issue.status = form.status.data
            issue.instructionBox = int(form.instructionBox.data)
            issue.instructions = form.instructions.data
            issue.active = int(form.active.data)
            # Attempt to store the issue
            result = issue.store()
            if result == True:
                return redirect(url_for("manage.manageIssues"))
            else:
                return "<h1>OOPS</h1><p>Something has gone utterley and terribly wrong. {}</p>".format(str(result))
        else:
            return "Did not validate"


    return render_template('manage/issue.html', form=form)

    


class issueForm(FlaskForm):
    title = StringField("Title: ", validators=[DataRequired()])
    description = TextAreaField("Description: ", validators=[DataRequired()])
    status = SelectField("Status: ",choices=[('Still Effecting','Still Effecting'),('Workaround','Workaround'),('Resolved','Resolved')], validators=[DataRequired()])
    instructionBox = BooleanField("Include Instructions: ")
    instructions = TextAreaField("Instructions: ")
    active = BooleanField("Active: ")
    submit = SubmitField("Submit")

techBoard/views/public.py
# views/public.py

# This view contains all of the resources for public facing views


import sys
sys.path.append("..")
from flask import Blueprint, render_template, session, request, jsonify
from flask_login import login_required

from techBoard.models.DBase import connection


# set blueprint
public = Blueprint('public', __name__)

# routes
# ========================================

# Homepage with search and featured
@public.route('/')
def home():
    return render_template('public/homepage.html')

@public.route('/issues')
def showIssues():
    try:
        c, conn = connection()
        c.execute("SELECT * FROM techBoard.issue WHERE active = 1;")
        result_set = c.fetchall()
        conn.close()

        return render_template('public/issues.html', issues=result_set)

    except Exception as e:
        return str(e)

    

techBoard/templates/site/header.html
{% block head %}

<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{{ url_for('static',filename='custom.css') }}">
  <!-- Menu Toggle Script -->
  <script>
    $(document).ready(function () {
      $("#menu-toggle").click(function () {
        //e.preventDefault();
        $("#wrapper").toggleClass("toggled");
      });
    });
  </script>
</head>
{% endblock %}
{% block navbar %}
<header>
  <div class="navbar navbar-expand-md navbar-dark bg-dark justify-content-start d-flex m-0" id="headerNav">
    <button class="navbar-toggler mr-auto" type="button" data-toggle="collapse" data-target="#navbarCollapse"
      aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <nav class="collapse navbar-collapse" id="navbarCollapse" role="navigation" aria-label="Main Menu">
      <ul id="menu-menu-1" class="navbar-nav align-content-center">
        <li class="nav-item m-2">
          <a class="nav-link" href={{url_for("public.showIssues")}}>
            <h3>Home</h3>
          </a>
        </li>
        <li class="nav-item m-2">
          <a class="nav-link" href="{{url_for("manage.manageIssues")}}">
            <h3>Issues</h3>
          </a>
        </li>
        <li class="nav-item m-2">
          <a class="nav-link" href={{url_for("manage.createIssue")}}>
            <h3>Create Issue</h3>
          </a>
        </li>
        {% if session['user_id'] %}
        <li class="nav-item dropdown m-2">
          <a class="nav-link dropdown-toggle h3 p-0" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
            aria-expanded="false">Account</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">My Account</a>
            <a class="dropdown-item" href={{ url_for("auth.logout") }}>Logout</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item m-2">
          <a class="nav-link" href={{url_for("auth.login")}}>
            <h3>Login</h3>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
  </div>
</header>
{% endblock %}

techBoard/templates/site/login.html
{% extends "bootstrap/base.html" %}
{% block title %}TechBoard{% endblock %}
{{ wtf.quick_form(form) }}
{% block content %}
<div class="container d-flex justify-content-around">
    <div class="card m-auto">
        <div class="card-body">
            <h2 class="card-title">Sign In</h2>
            <form method="POST">
                {{ form.csrf_token }}
                <div class="form-group ">
                    {{ form.username.label }} {{ form.username(class_="form-control form-control-lg") }}
                </div>
                <div class="form-group">
                    {{ form.password.label }} {{ form.password(class_="form-control form-control-lg") }}
                </div>
                <div class="form-group">
                    <button class="btn btn-lg btn-primary" type="submit">Login</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
{{ message }}
{% endfor %}
{% endif %}
{% endwith %}
{% endblock %}
{% block footer %}

{% endblock %}